### ISSUE TITLE
Vendor boolector inside the repo

### ISSUE THREAD

**Issue by finga** [cdisselkoen/boolector-rs#2]
Hello,

wouldn't it make sense to also vendor boolector?
For example like https://github.com/gyscos/zstd-rs does it with https://github.com/facebook/zstd?

**Comment by cdisselkoen** [comment]
Hi!  Boolector is already vendored by the `boolector-sys` repo (https://github.com/fatemender/boolector-sys), which we depend on.  I think it makes more sense to have it there, since `boolector-sys` is the crate that generates the raw bindings etc.  It looks to me that in your example the single repo `zstd-rs` contains the source for both `zstd` and `zstd-sys` crates, but in our case here the low-level and high-level bindings live in separate repos with different maintainers.

**Comment by finga** [comment]
Oh, I overlooked that. Thanks for pointing that out.
